# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechAdminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tech_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_entry', models.CharField(max_length=255)),
                ('tuning_notes', models.CharField(max_length=255)),
                ('repairs', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Tech_Admin',
        ),
    ]
