# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 01:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Piano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=30)),
                ('mod', models.CharField(choices=[('grand', 'Grand'), ('old upright', 'Old Upright'), ('console', 'Console'), ('studio', 'Studio'), ('spinet', 'Spinet')], max_length=30)),
                ('serial_num', models.CharField(blank=True, max_length=30, null=True)),
                ('size', models.CharField(blank=True, max_length=30, null=True)),
                ('last_serviced', models.DateField(blank=True, null=True)),
                ('service_request', models.CharField(blank=True, choices=[('tune', 'Tune'), ('repair', 'Repair'), ('key services', 'Key Services'), ('regulation', 'Regulation'), ('voicing', 'Voicing'), ('cleaning', 'Cleaning'), ('restoration', 'Restoration'), ('appraisal', 'Appraisal'), ('purchase evaluation', 'Purchasing Evaluation'), ('humidity control', 'Humidity Control'), ('annual contract', 'Annual Contract')], max_length=30, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule_Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('service_performed', models.CharField(max_length=255)),
                ('service_hours', models.CharField(max_length=10)),
                ('service_count', models.CharField(max_length=10)),
                ('service_cost', models.CharField(max_length=10)),
                ('service_notify', models.CharField(max_length=10)),
                ('piano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreatPSapp.Piano')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_contract', models.CharField(max_length=20)),
            ],
        ),
    ]
