# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=30)),
                ('mod', models.CharField(choices=[('grand', 'Grand'), ('old upright', 'Old Upright'), ('console', 'Console'), ('studio', 'Studio'), ('spinet', 'Spinet')], max_length=30)),
                ('serial_num', models.CharField(blank=True, max_length=30, null=True)),
                ('size', models.CharField(blank=True, max_length=30, null=True)),
                ('last_serviced', models.DateField(blank=True, null=True)),
                ('service_request', models.CharField(blank=True, choices=[('tune', 'Tune'), ('repair', 'Repair'), ('key services', 'Key Services'), ('regulation', 'Regulation'), ('voicing', 'Voicing'), ('cleaning', 'Cleaning'), ('restoration', 'Restoration'), ('appraisal', 'Appraisal'), ('purchase evaluation', 'Purchasing Evaluation'), ('humidity control', 'Humidity Control'), ('annual contract', 'Annual Contract')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('cell_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('work_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('day', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('service_performed', models.CharField(max_length=255)),
                ('service_hours', models.CharField(max_length=10)),
                ('service_count', models.CharField(max_length=10)),
                ('service_cost', models.CharField(max_length=10)),
                ('service_notify', models.CharField(max_length=10)),
                ('piano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreatPSapp.Piano')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.CharField(max_length=255)),
                ('requested_time', models.CharField(max_length=255)),
                ('pref_date_time', models.CharField(max_length=255)),
                ('tune', models.CharField(blank=True, max_length=20, null=True)),
                ('regulation', models.CharField(blank=True, max_length=20, null=True)),
                ('repair', models.CharField(blank=True, max_length=20, null=True)),
                ('key_services', models.CharField(blank=True, max_length=20, null=True)),
                ('cleaning', models.CharField(blank=True, max_length=20, null=True)),
                ('appraisal', models.CharField(blank=True, max_length=20, null=True)),
                ('humidity_control', models.CharField(blank=True, max_length=20, null=True)),
                ('purchase_consulting', models.CharField(blank=True, max_length=20, null=True)),
                ('annual_contract', models.CharField(max_length=20)),
            ],
        ),
    ]
