# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreatPSapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piano',
            old_name='style',
            new_name='size',
        ),
    ]
