# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreatPSapp', '0002_auto_20170726_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_request',
            name='humidity_control',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
