# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreatPSapp', '0002_auto_20170718_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piano',
            name='last_serviced',
            field=models.DateField(blank=True, null=True),
        ),
    ]
