# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreatPSapp', '0003_service_request_humidity_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_request',
            name='purchase_consulting',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
