# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreatPSapp', '0003_auto_20170718_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piano',
            name='serial_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
