# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreatPSapp', '0004_auto_20170718_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piano',
            name='mod',
            field=models.CharField(choices=[('grand', 'Grand'), ('upright', 'Upright'), ('studio', 'Studio'), ('spinet', 'Spinet')], max_length=30),
        ),
        migrations.AlterField(
            model_name='piano',
            name='serial_num',
            field=models.CharField(max_length=30),
        ),
    ]
