# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreatPSapp', '0004_service_request_purchase_consulting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule_Appointment',
            new_name='Scheduling',
        ),
    ]
