# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreatPSapp', '0005_auto_20170909_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_request',
            name='pref_date_time',
            field=models.CharField(default='temp', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service_request',
            name='requested_date',
            field=models.CharField(default='temp', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service_request',
            name='requested_time',
            field=models.CharField(default='temp', max_length=255),
            preserve_default=False,
        ),
    ]
