# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreatPSapp', '0006_piano_customerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piano',
            name='customerID',
        ),
    ]
