# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreatPSapp', '0006_auto_20170917_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piano',
            name='client',
        ),
    ]
