# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreatPSapp', '0008_service_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service_Request',
        ),
    ]
