# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreatPSapp', '0009_scheduling_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedulings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
