# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreatPSapp', '0009_delete_service_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(choices=[('tune', 'Tune'), ('repair', 'Repair'), ('regulation', 'Regulation'), ('voicing', 'Voicing'), ('tune', 'Tune'), ('repair', 'Repair'), ('regulation', 'Regulation'), ('voicing', 'Voicing'), ('cleaning', 'Cleaning'), ('appraisal', 'Appraisal'), ('purchasing', 'Purchasing'), ('humidity control', 'Humidity Control')], max_length=30)),
            ],
        ),
    ]
