# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreatPSapp', '0010_service_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service_Request',
            new_name='Request',
        ),
    ]
