# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreatPSapp', '0010_schedulings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedulings',
        ),
    ]
