# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 03:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreatPSapp', '0011_auto_20170719_2030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='ServiceRequest',
        ),
    ]
