# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreatPSapp', '0012_auto_20170719_2036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
        migrations.AddField(
            model_name='piano',
            name='request',
            field=models.CharField(blank=True, choices=[('tune', 'Tune'), ('repair', 'Repair'), ('regulation', 'Regulation'), ('voicing', 'Voicing'), ('tune', 'Tune'), ('repair', 'Repair'), ('regulation', 'Regulation'), ('voicing', 'Voicing'), ('cleaning', 'Cleaning'), ('appraisal', 'Appraisal'), ('purchasing', 'Purchasing'), ('humidity control', 'Humidity Control')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='piano',
            name='serial_num',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='piano',
            name='size',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
