# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GreatPSapp', '0016_auto_20170719_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('service_performed', models.CharField(max_length=255)),
                ('service_hours', models.CharField(max_length=10)),
                ('service_count', models.CharField(max_length=10)),
                ('service_cost', models.CharField(max_length=10)),
                ('service_notify', models.CharField(max_length=10)),
                ('piano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreatPSapp.Piano')),
            ],
        ),
    ]
