# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreatPSapp', '0017_service_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piano',
            name='service_request',
            field=models.CharField(blank=True, choices=[('tune', 'Tune'), ('repair', 'Repair'), ('key services', 'Key Services'), ('regulation', 'Regulation'), ('voicing', 'Voicing'), ('cleaning', 'Cleaning'), ('restoration', 'Restoration'), ('appraisal', 'Appraisal'), ('purchase evaluation', 'Purchasing Evaluation'), ('humidity control', 'Humidity Control'), ('annual contract', 'Annual Contract')], max_length=30, null=True),
        ),
    ]
