# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreatPSapp', '0018_auto_20170720_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_contract', models.CharField(max_length=20)),
            ],
        ),
    ]
