# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreatPSapp', '0019_service_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule_Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='service_record',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
