# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreatPSapp', '0020_auto_20170721_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piano',
            name='mod',
            field=models.CharField(choices=[('grand', 'Grand'), ('old upright', 'Old Upright'), ('console', 'Console'), ('studio', 'Studio'), ('spinet', 'Spinet')], max_length=30),
        ),
    ]
