# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_auto_20170712_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=30)),
                ('mod', models.CharField(max_length=30)),
                ('style', models.CharField(max_length=30)),
                ('serial_num', models.IntegerField(max_length=50)),
            ],
        ),
    ]
