# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0003_piano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piano',
            name='serial_num',
            field=models.IntegerField(),
        ),
    ]
