# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 04:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0004_auto_20170717_0113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Piano',
        ),
    ]
