# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 04:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0007_user_customerid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
