# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0008_auto_20170924_2119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
